name: The Team Room
favicon: null
layout_spectrum: 0.8211672615725547
typography_spectrum: 0.4133282208349556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7306544024031609
  lightness: 0.31659254617989063
  saturation: 0.24102097074501216
  rhythmicContrast: 0.11103196744807065
purpose: []
